- name: Ensure GitLab host prerequisites
  ansible.builtin.import_tasks: system.yml

- name: Install GitLab packages
  ansible.builtin.import_tasks: packages.yml

- name: Configure GitLab
  ansible.builtin.import_tasks: configure.yml

- name: Provision GitLab admin users
  ansible.builtin.import_tasks: users.yml
