- name: Install dependencies
  apt:
    name:
      - curl
      - ca-certificates
      - openssh-server
      - tzdata
      - perl
      - postfix
    state: present
    update_cache: true

- name: Add GitLab repository
  shell: curl -fsSL https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
  args:
    creates: /etc/apt/sources.list.d/gitlab_gitlab-ce.list

- name: Install GitLab CE
  apt:
    name: gitlab-ce
    state: present
    update_cache: true
  environment:
    EXTERNAL_URL: "{{ gitlab_external_url }}"

- name: Configure GitLab
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      external_url '{{ gitlab_external_url }}'
      gitlab_rails['gitlab_signup_enabled'] = false
      gitlab_rails['gitlab_default_can_create_group'] = true
      gitlab_rails['gitlab_email_enabled'] = false
      registry_external_url '{{ gitlab_registry_url }}'
      gitlab_rails['initial_root_password'] = 'P@SSW0RD'
  notify: Reconfigure GitLab
