- name: Reload NFS exports
  ansible.builtin.command:
    cmd: exportfs -ra
  changed_when: true

- name: Restart NFS server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
