- name: Initialize Docker Swarm on the primary manager
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ hostvars[groups['swarm_managers'][0]].ansible_host }}"
  when: inventory_hostname == groups['swarm_managers'][0]

- name: Get current worker join token from the primary manager
  community.docker.docker_swarm_info:
  delegate_to: "{{ groups['swarm_managers'][0] }}"
  run_once: true
  register: docker_swarm_primary_manager_swarm_info
  when: groups['swarm_workers'] | length > 0

- name: Join worker nodes to the swarm
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ ansible_host }}"
    join_token: "{{ docker_swarm_primary_manager_swarm_info.swarm_facts.JoinTokens.Worker }}"
    remote_addrs:
      - "{{ hostvars[groups['swarm_managers'][0]].ansible_host }}:2377"
  when: inventory_hostname in groups['swarm_workers']
