- name: Apply configured node labels
  community.docker.docker_node:
    hostname: "{{ hostvars[item.key].ansible_hostname }}"
    labels: "{{ item.value }}"
  loop: "{{ swarm_node_labels | default({}) | dict2items }}"
  when: inventory_hostname == groups['swarm_managers'][0]
