version: "3.9"

services:
  mariadb-preprod:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: quantum_motors
      MARIADB_USER: quantum
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_preprod_data:/var/lib/mysql
    configs:
      - source: mariadb_seed_sql
        target: /docker-entrypoint-initdb.d/01-init.sql
    networks:
      - preprod_net
    deploy:
      placement:
        constraints:
          - node.labels.db-node == true
      resources:
        reservations:
          cpus: "0.25"
          memory: 384M
        limits:
          cpus: "1.00"
          memory: 1024M

  api-preprod:
    image: ${CI_REGISTRY_IMAGE}/backend:${IMAGE_TAG}
    environment:
      DATABASE_URL: mysql://quantum:${DB_PASSWORD}@mariadb-preprod:3306/quantum_motors
      PORT: 3000
      HOST: 0.0.0.0
      CORS_ORIGIN: http://preprod.quantum.local
      CAR_SERVICE_IMAGE_URL: http://api-preprod.quantum.local
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NODE_ENV: production
    networks:
      - preprod_net
      - public
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 128M
        limits:
          cpus: "0.50"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.api-preprod.rule=Host(`api-preprod.quantum.local`)
        - traefik.http.routers.api-preprod.entrypoints=web
        - traefik.http.services.api-preprod.loadbalancer.server.port=3000

  front-preprod:
    image: ${CI_REGISTRY_IMAGE}/frontend:${IMAGE_TAG}
    environment:
      API_URL_INTERNAL: http://api-preprod:3000
      HOST: 0.0.0.0
      PORT: 4200
      NODE_ENV: production
    networks:
      - preprod_net
      - public
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 128M
        limits:
          cpus: "0.50"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.front-preprod.rule=Host(`preprod.quantum.local`)
        - traefik.http.routers.front-preprod.entrypoints=web
        - traefik.http.services.front-preprod.loadbalancer.server.port=4200

networks:
  preprod_net:
    external: true
    name: preprod_net
  public:
    external: true
    name: public

volumes:
  mariadb_preprod_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4,soft,rw
      device: ":${NFS_EXPORTS_ROOT}/preprod/mariadb"

configs:
  mariadb_seed_sql:
    file: ../clo5-backend-master/quantum-motors-initial.sql
