services:
  api-prod-blue:
    image: ${CI_REGISTRY_IMAGE}/backend:${IMAGE_TAG}
    environment:
      DATABASE_URL: mysql://quantum:${DB_PASSWORD}@mariadb-prod:3306/quantum_motors
      PORT: 3000
      HOST: 0.0.0.0
      CORS_ORIGIN: http://front.quantum.local
      CAR_SERVICE_IMAGE_URL: http://api.quantum.local
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NODE_ENV: production
    networks:
      - prod_net
      - public
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 128M
        limits:
          cpus: "0.50"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.api-blue.rule=Host(`api-blue.quantum.local`)
        - traefik.http.routers.api-blue.entrypoints=web
        - traefik.http.routers.api-blue.service=api-blue
        - traefik.http.services.api-blue.loadbalancer.server.port=3000
        - traefik.http.routers.api-live-blue.rule=Host(`api.quantum.local`)
        - traefik.http.routers.api-live-blue.entrypoints=web
        - traefik.http.routers.api-live-blue.service=api-live-blue
        - traefik.http.services.api-live-blue.loadbalancer.server.port=3000

  front-prod-blue:
    image: ${CI_REGISTRY_IMAGE}/frontend:${IMAGE_TAG}
    environment:
      API_URL_INTERNAL: http://api-prod-blue:3000
      HOST: 0.0.0.0
      PORT: 4200
      NODE_ENV: production
    networks:
      - prod_net
      - public
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 128M
        limits:
          cpus: "0.50"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.front-blue.rule=Host(`front-blue.quantum.local`)
        - traefik.http.routers.front-blue.entrypoints=web
        - traefik.http.routers.front-blue.service=front-blue
        - traefik.http.services.front-blue.loadbalancer.server.port=4200
        - traefik.http.routers.front-live-blue.rule=Host(`front.quantum.local`)
        - traefik.http.routers.front-live-blue.entrypoints=web
        - traefik.http.routers.front-live-blue.service=front-live-blue
        - traefik.http.services.front-live-blue.loadbalancer.server.port=4200

networks:
  prod_net:
    external: true
    name: prod_net
  public:
    external: true
    name: public
