all:
  vars:
    ansible_become: true

  children:
    swarm_managers:
      hosts:
        vm1:
          ansible_host: 172.16.248.64
          ansible_user: teixei_t

    swarm_workers:
      hosts:
        vm2:
          ansible_host: 172.16.248.92
          ansible_user: teixei_t
        vm3:
          ansible_host: 172.16.248.97
          ansible_user: touahr_s

    sonarqube_nodes:
      hosts:
        vm3:

    logging_nodes:
      hosts:
        vm3:

    gitlab:
      hosts:
        vm4:
          ansible_host: 172.16.248.236
          ansible_user: touahr_s
