docker_packages:
  - docker.io
  - python3-docker

docker_swarm_daemon_config:
  insecure-registries:
    - "172.16.248.236:5050"

swarm_node_labels:
  vm2:
    db-node: "true"
  vm3:
    sonarqube: "true"
    logging: "true"

overlay_networks:
  - public
  - preprod_net
  - prod_net
  - logs_net

nfs_exports_root: /srv/nfs/quantum-motors
nfs_export_directories:
  - preprod/mariadb
  - prod/mariadb
nfs_allowed_cidr: 172.16.248.0/24

traefik_stack_name: traefik

sonarqube_service_name: sonarqube
sonarqube_image: sonarqube:lts-community
sonarqube_port: 9000
sonarqube_resources:
  reservations:
    cpus: 0.50
    memory: 1024M
  limits:
    cpus: 1.50
    memory: 1536M
sonarqube_mounts:
  - source: /srv/sonarqube/data
    target: /opt/sonarqube/data
    type: bind
  - source: /srv/sonarqube/extensions
    target: /opt/sonarqube/extensions
    type: bind
  - source: /srv/sonarqube/logs
    target: /opt/sonarqube/logs
    type: bind

logging_stack_name: logging
loki_data_dir: /srv/loki
alloy_data_dir: /srv/alloy
grafana_logs_data_dir: /srv/grafana

gitlab_external_url: "http://172.16.248.236"
gitlab_registry_url: "http://172.16.248.236:5050"
gitlab_runner_registration_token: "{{ vault_gitlab_runner_registration_token | default('') }}"

gitlab_admin_users:
  - username: teixei_t
    name: teixei_t
    email: teixei_t@quantum.local
  - username: touahr_s
    name: touahr_s
    email: touahr_s@quantum.local
