docker_packages:
  - docker.io
  - python3-docker

docker_swarm_daemon_config:
  insecure-registries:
    - "172.16.248.236:5050"

overlay_networks:
  - public
  - preprod_net
  - prod_net

nfs_exports_root: /srv/nfs/quantum-motors
nfs_export_directories:
  - preprod/mariadb
  - prod/mariadb
nfs_allowed_cidr: 172.16.248.0/24

traefik_stack_name: traefik

sonarqube_service_name: sonarqube
sonarqube_image: sonarqube:lts-community
sonarqube_port: 9000
sonarqube_mounts:
  - source: /srv/sonarqube/data
    target: /opt/sonarqube/data
    type: bind
  - source: /srv/sonarqube/extensions
    target: /opt/sonarqube/extensions
    type: bind
  - source: /srv/sonarqube/logs
    target: /opt/sonarqube/logs
    type: bind

gitlab_external_url: "http://172.16.248.236"
gitlab_registry_url: "http://172.16.248.236:5050"
gitlab_runner_registration_token: "{{ vault_gitlab_runner_registration_token | default('') }}"

gitlab_admin_users:
  - username: rafina_d
    name: rafina_d
    email: rafina_d@local.test
  - username: rinaz_a
    name: rinaz_a
    email: rinaz_a@local.test
